Bookmarks features and changes for issue #40
sassoftware/sas-portal-app pull request #42
Opened 2024-10-10 14:48 UTC by sajarix

Resolving issue #2, #39 and #40

2024-11-22 12:12 UTC, gh4nh commented
Test comment 22. Nov.

2024-11-22 12:19 UTC, CraigRubendall requested changes
several items that should be changed/fixed before accepting this request.

2024-11-26 11:02 UTC, sajarix commented on sas/SASEnvironment/Files/portal/genPortalMain.xslt
> +   <xsl:variable name="stpLocation">
I'm going to do the adjustment as you have suggested.

2024-11-26 11:03 UTC, sajarix commented on sas/SASEnvironment/Files/portal/genPortalMain.xslt
> +         <xsl:variable name="stpLocation">
I'm going to do the adjustment as you have suggested.

2024-11-26 11:21 UTC, sajarix commented on sas/SASEnvironment/Files/portlet/update.bookmarks.xslt
I'm going to do the adjustment as you have suggested.

2025-03-13 17:07 UTC, CraigRubendall commented
changes made by this pull request have been integrated manually do issues merging.

2025-03-13 17:07 UTC, closed without merging